### ISSUE TITLE
Doesn't work on MacOS. multiprocessing not supported

### ISSUE THREAD

**Issue by arianvp** [tweag/nixtract#20]
**Describe the bug**

**To Reproduce**
```
 % nixtract --target-flake-ref nixpkgs --target-attribute-path nodejs out
Exception in thread Thread-6 (queue_processor):
Traceback (most recent call last):
  File "/nix/store/1c51gjbaq6hlqmm6w735naks06dg4c1x-python3-3.10.11/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/nix/store/1c51gjbaq6hlqmm6w735naks06dg4c1x-python3-3.10.11/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/nix/store/9c3v4lq81z8sp07i8si9m8syp1xkcz63-python3.10-nixtract-cli-0.1.0/lib/python3.10/site-packages/nixtract/cli.py", line 211, in queue_processor
    queue.qsize(),
  File "/nix/store/1c51gjbaq6hlqmm6w735naks06dg4c1x-python3-3.10.11/lib/python3.10/multiprocessing/queues.py", line 126, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
Finished but queue is not empt
```

**Expected behavior**
It works

**Environment**
 - OS name + version:  MacOS SOnoma 14.2.1
 - Version of the code:

**Additional context**

https://stackoverflow.com/questions/65609529/python-multiprocessing-queue-notimplementederror-macos provides some hints how to fix this

**Comment by GuillaumeDesforges** [comment]
Thanks for reporting. We'll try to fix that asap :+1:
